require('dotenv').config();
const mongoose = require('mongoose');
const Profile = require('./models/Profile');
const Project = require('./models/Project');
const BlogPost = require('./models/BlogPost');
const StateDistrict = require('./models/StateDistrict');
const SiteSettings = require('./models/SiteSettings');

const mongoURI = process.env.MONGODB_URI || 'mongodb+srv://fbglministries2016_db_user:LuyNgH2gPY7fuOi9@cluster0.zw4qyzh.mongodb.net/?appName=Cluster0';

const seedDatabase = async () => {
  try {
    console.log('Connecting to database...');
    const bcrypt = require('bcryptjs');
    const defaultPassword = await bcrypt.hash('asdf1234', 10);
    try {
      await mongoose.connect(mongoURI, { serverSelectionTimeoutMS: 5000 });
      console.log('Connected to MongoDB Atlas Cloud.');
    } catch (atlasErr) {
      console.warn('⚠️ MongoDB Atlas connection failed:', atlasErr.message);
      console.log('🔄 Trying to connect to local MongoDB (mongodb://127.0.0.1:27017/fbgl)...');
      await mongoose.connect('mongodb://127.0.0.1:27017/fbgl', { serverSelectionTimeoutMS: 5000 });
      console.log('Connected to Local MongoDB.');
    }

    // 1. Clear database
    console.log('Clearing existing data...');
    await Promise.all([
      Profile.deleteMany({}),
      Project.deleteMany({}),
      BlogPost.deleteMany({}),
      StateDistrict.deleteMany({}),
      SiteSettings.deleteMany({})
    ]);
    console.log('Database cleared.');

    // 2. Insert Site Settings
    console.log('Seeding site settings...');
    const settings = new SiteSettings({
      show_all_projects_on_home: true,
      banner_title: 'FIRST BORN GOSPEL LIFE MINISTRIES',
      banner_subtitle: 'Transforming Lives through Social, Economic & Educational Empowerment in Christ'
    });
    await settings.save();

    // 3. Insert State Districts
    console.log('Seeding state districts...');
    await Promise.all([
      new StateDistrict({ state: 'AP', district: 'EG' }).save(),
      new StateDistrict({ state: 'KA', district: 'BLR' }).save(),
      new StateDistrict({ state: 'TS', district: 'HYD' }).save()
    ]);

    // 4. Insert Profiles
    console.log('Seeding profiles...');
    const profilesData = [
    {
        "_id": "admin_user_uid",
        "name": "Super Admin",
        "email": "admin@fbglministry.org",
        "username": "admin@fbglministry.org",
        "password": "asdf1234",
        "role": "admin",
        "position": "Administrator",
        "id_no": "FBGL-AP-EG-ADMIN-01",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "FBGL Ministry Headquarters, Rajahmundry, East Godavari, AP",
        "phone": "+91-9876543210",
        "aadhaar_no": "123456789012"
    },
    {
        "_id": "board_member_1_uid",
        "name": "Sample Board Member 1",
        "email": "boardmember1@fbglministry.org",
        "username": "boardmember1@fbglministry.org",
        "password": "asdf1234",
        "role": "board_member",
        "position": "Founder & President",
        "bio": "Sample Board Member 1 serves as Founder & President, leading strategic community outreach initiatives.",
        "id_no": "FBGL-BOARD-01",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "FBGL Headquarters, East Godavari, AP",
        "phone": "+91-9876543211",
        "aadhaar_no": "123456789013",
        "profile_picture": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=250"
    },
    {
        "_id": "board_member_2_uid",
        "name": "Sample Board Member 2",
        "email": "boardmember2@fbglministry.org",
        "username": "boardmember2@fbglministry.org",
        "password": "asdf1234",
        "role": "board_member",
        "position": "Vice President",
        "bio": "Sample Board Member 2 serves as Vice President, overseeing organizational governance and partnership development.",
        "id_no": "FBGL-BOARD-02",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "FBGL Headquarters, East Godavari, AP",
        "phone": "+91-9876543212",
        "aadhaar_no": "123456789014",
        "profile_picture": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=250"
    },
    {
        "_id": "area_manager_mude_rajesh_uid",
        "name": "Mude Rajesh",
        "email": "mude.rajesh.rajahmundry@fbglministry.org",
        "username": "mude.rajesh.rajahmundry@fbglministry.org",
        "password": "asdf1234",
        "role": "area_manager",
        "position": "Area Manager",
        "id_no": "FBGL-AP-EG-AM-01",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "D.No: 66-15-28/1, Gadilavaddi Nagar, Rajahmundry",
        "phone": "+91-8885776832",
        "aadhaar_no": "686568886634",
        "bio": "Mude Rajesh serves as Area Manager overseeing operations across Mandals in East Godavari district."
    },
    {
        "_id": "project_manager_panta_satyanarayana_uid",
        "name": "Panta Satyanarayana",
        "email": "panta.satyanarayana.rajahmundry@fbglministry.org",
        "username": "panta.satyanarayana.rajahmundry@fbglministry.org",
        "password": "asdf1234",
        "role": "project_manager",
        "position": "Project Manager",
        "id_no": "FBGL-AP-EG-PM-01",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "1-145, Bommuru Leprosy Colony, Rajahmundry, 533124",
        "phone": "+91-7995422658",
        "aadhaar_no": "282983418258",
        "bio": "Panta Satyanarayana serves as Project Manager overseeing field projects and coordinating Social Workers."
    },
    {
        "_id": "social_worker_1_uid",
        "name": "Vemana Venkateswara Rao (Sudheer)",
        "email": "vemana.venkateswara.rao.sudheer.atreyapuram@fbglministry.org",
        "username": "vemana.venkateswara.rao.sudheer.atreyapuram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-01",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Peravaram, Govidi Peta, Atreyapuram Mandal, Dr. B.R. Ambedkar Konaseema Dist, 533235, A.P.",
        "phone": "+91-9014971125",
        "aadhaar_no": "676154974613",
        "bio": "Vemana Venkateswara Rao (Sudheer) serves as Social Worker in Atreyapuram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_2_uid",
        "name": "Addanki Nooka Raju",
        "email": "addanki.nooka.raju.atreyapuram@fbglministry.org",
        "username": "addanki.nooka.raju.atreyapuram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-02",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Velicheru, New Colony, Atreyapuram Mandal, Dr. B.R. Ambedkar Konaseema Dist, 533235, AP",
        "phone": "+91-9133048417",
        "aadhaar_no": "674436230148",
        "bio": "Addanki Nooka Raju serves as Social Worker in Atreyapuram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_3_uid",
        "name": "Barkula Sreenuvasa Rao",
        "email": "barkula.sreenuvasa.rao.devipatnam@fbglministry.org",
        "username": "barkula.sreenuvasa.rao.devipatnam@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-03",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "S/o Markandeyulu, 1-102 Devipatnam, 533339",
        "phone": "+91-9493264325",
        "aadhaar_no": "435007265507",
        "bio": "Barkula Sreenuvasa Rao serves as Social Worker in Devipatnam Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_4_uid",
        "name": "Attla Sitaramula (Telugu Script Name)",
        "email": "attla.sitaramula.telugu.script.name.devipatnam@fbglministry.org",
        "username": "attla.sitaramula.telugu.script.name.devipatnam@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-04",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Indukurupeta, Devipatnam Mandal",
        "phone": "+91-6304485753",
        "aadhaar_no": "613823158418",
        "bio": "Attla Sitaramula (Telugu Script Name) serves as Social Worker in Devipatnam Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_5_uid",
        "name": "Kodi Sunny Babu",
        "email": "kodi.sunny.babu.devipatnam@fbglministry.org",
        "username": "kodi.sunny.babu.devipatnam@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-05",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "1-108, Thoyyeru, Devipatnam (M), 533339",
        "phone": "+91-9704937564",
        "aadhaar_no": "579069842898",
        "bio": "Kodi Sunny Babu serves as Social Worker in Devipatnam Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_6_uid",
        "name": "Peduri Moshe",
        "email": "peduri.moshe.gkmmandal@fbglministry.org",
        "username": "peduri.moshe.gkmmandal@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-06",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "George Gopalapuram Village, GKM Mandal",
        "phone": "+91-9666770481",
        "aadhaar_no": "123456781005",
        "bio": "Peduri Moshe serves as Social Worker in GKM Mandal Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_7_uid",
        "name": "SrimaanKulu Vijayachandra",
        "email": "srimaankulu.vijayachandra.gandepalli@fbglministry.org",
        "username": "srimaankulu.vijayachandra.gandepalli@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-07",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Murari Post, Gandepalli Mandal, Kakinada District",
        "phone": "+91-9989769372",
        "aadhaar_no": "254225370481",
        "bio": "SrimaanKulu Vijayachandra serves as Social Worker in Gandepalli Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_8_uid",
        "name": "Vadlapati Amseenidhsen",
        "email": "vadlapati.amseenidhsen.gandepalli@fbglministry.org",
        "username": "vadlapati.amseenidhsen.gandepalli@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-08",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Gandepalli Post, Kakinada District",
        "phone": "+91-9441563587",
        "aadhaar_no": "266777293096",
        "bio": "Vadlapati Amseenidhsen serves as Social Worker in Gandepalli Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_9_uid",
        "name": "Kandikatla Chakrapani (Daiva Aseervadam)",
        "email": "kandikatla.chakrapani.daiva.aseervadam.gandepalli@fbglministry.org",
        "username": "kandikatla.chakrapani.daiva.aseervadam.gandepalli@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-09",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Murari Post, Gandepalli Mandal, Kakinada District",
        "phone": "+91-7981983183",
        "aadhaar_no": "409150688591",
        "bio": "Kandikatla Chakrapani (Daiva Aseervadam) serves as Social Worker in Gandepalli Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_10_uid",
        "name": "Kommu Veerraju",
        "email": "kommu.veerraju.gandepalli@fbglministry.org",
        "username": "kommu.veerraju.gandepalli@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-10",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Talluru Post, Gandepalli Mandal, Kakinada",
        "phone": "+91-9515779225",
        "aadhaar_no": "807021143849",
        "bio": "Kommu Veerraju serves as Social Worker in Gandepalli Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_11_uid",
        "name": "Bachala Mahima Raju",
        "email": "bachala.mahima.raju.gandepalli@fbglministry.org",
        "username": "bachala.mahima.raju.gandepalli@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-11",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Mallepalli, Gandepalli Mandal",
        "phone": "+91-9705684591",
        "aadhaar_no": "123456781010",
        "bio": "Bachala Mahima Raju serves as Social Worker in Gandepalli Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_12_uid",
        "name": "Gudala Madhu",
        "email": "gudala.madhu.gandepalli@fbglministry.org",
        "username": "gudala.madhu.gandepalli@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-12",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Gandepalli Mandal, Kakinada Dist",
        "phone": "+91-9704527959",
        "aadhaar_no": "123456781011",
        "bio": "Gudala Madhu serves as Social Worker in Gandepalli Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_13_uid",
        "name": "Ladi Srinu (Syman)",
        "email": "ladi.srinu.syman.gangavaram@fbglministry.org",
        "username": "ladi.srinu.syman.gangavaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-13",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "14-45, Ambedkar Street, Gokavaram, E.G. Dist, Andhra Pradesh",
        "phone": "+91-8330967769",
        "aadhaar_no": "419093508446",
        "bio": "Ladi Srinu (Syman) serves as Social Worker in Gangavaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_14_uid",
        "name": "Orlankala Veera Raghavarao (Nataniel)",
        "email": "orlankala.veera.raghavarao.nataniel.gangavaram@fbglministry.org",
        "username": "orlankala.veera.raghavarao.nataniel.gangavaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-14",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Mallikharjuna Nagar, 57-8-63, Near Bethel High School, Rajahmundry - 533105",
        "phone": "+91-7997178363",
        "aadhaar_no": "123456781013",
        "bio": "Orlankala Veera Raghavarao (Nataniel) serves as Social Worker in Gangavaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_15_uid",
        "name": "Maddala Nageswara Rao (Rajpal)",
        "email": "maddala.nageswara.rao.rajpal.gokavaram@fbglministry.org",
        "username": "maddala.nageswara.rao.rajpal.gokavaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-15",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Yedurupaka, Gokavaram Mandal",
        "phone": "+91-6305745668",
        "aadhaar_no": "123456781014",
        "bio": "Maddala Nageswara Rao (Rajpal) serves as Social Worker in Gokavaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_16_uid",
        "name": "Chirra Prakash Rao",
        "email": "chirra.prakash.rao.korukonda@fbglministry.org",
        "username": "chirra.prakash.rao.korukonda@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-16",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Gadala (Po), Korukonda (Mandal)",
        "phone": "+91-9949332697",
        "aadhaar_no": "405421107799",
        "bio": "Chirra Prakash Rao serves as Social Worker in Korukonda Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_17_uid",
        "name": "Chirra Yakob (Posiyya)",
        "email": "chirra.yakob.posiyya.korukonda@fbglministry.org",
        "username": "chirra.yakob.posiyya.korukonda@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-17",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Gadala",
        "phone": "+91-8523097773",
        "aadhaar_no": "647922636349",
        "bio": "Chirra Yakob (Posiyya) serves as Social Worker in Korukonda Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_18_uid",
        "name": "Chirra Vijaya Babu",
        "email": "chirra.vijaya.babu.korukonda@fbglministry.org",
        "username": "chirra.vijaya.babu.korukonda@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-18",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Door No: 2-215, Gadala, Korukonda (MD), E.G. Dt, 533102",
        "phone": "+91-8317631321",
        "aadhaar_no": "123456781017",
        "bio": "Chirra Vijaya Babu serves as Social Worker in Korukonda Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_19_uid",
        "name": "Ketha Krishnarjun [Elisha]",
        "email": "ketha.krishnarjun.elisha.korukonda@fbglministry.org",
        "username": "ketha.krishnarjun.elisha.korukonda@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-19",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "4-82, Gadarada Raja Street, Korukonda Mandalam, East Godavari - 533289",
        "phone": "+91-8106060311",
        "aadhaar_no": "492123252433",
        "bio": "Ketha Krishnarjun [Elisha] serves as Social Worker in Korukonda Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_20_uid",
        "name": "Viswanadhuni Arjuna Rao",
        "email": "viswanadhuni.arjuna.rao.korukonda@fbglministry.org",
        "username": "viswanadhuni.arjuna.rao.korukonda@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-20",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "2-212/1, Srirangapatnam, Korukonda Mandal",
        "phone": "+91-7032544121",
        "aadhaar_no": "601860739626",
        "bio": "Viswanadhuni Arjuna Rao serves as Social Worker in Korukonda Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_21_uid",
        "name": "Kandregula Jayaraju Venkanna Babu",
        "email": "kandregula.jayaraju.venkanna.babu.korukonda@fbglministry.org",
        "username": "kandregula.jayaraju.venkanna.babu.korukonda@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-21",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "S/o Venkata Ramana, Ramabhadra Gari Street, Dr. No. 5-135, Dosakayalapalli",
        "phone": "+91-9492387294",
        "aadhaar_no": "123456781020",
        "bio": "Kandregula Jayaraju Venkanna Babu serves as Social Worker in Korukonda Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_22_uid",
        "name": "Chatla Srinivas",
        "email": "chatla.srinivas.korukonda@fbglministry.org",
        "username": "chatla.srinivas.korukonda@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-22",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "S/o Chatla Bhushanam, D.No: 4-97, Narsapuram Village, Korukonda Mandal, East Godavari, A.P.",
        "phone": "+91-9704411569",
        "aadhaar_no": "386400406263",
        "bio": "Chatla Srinivas serves as Social Worker in Korukonda Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_23_uid",
        "name": "Doddi Daniel (Telugu Script Name)",
        "email": "doddi.daniel.telugu.script.name.korukonda@fbglministry.org",
        "username": "doddi.daniel.telugu.script.name.korukonda@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-23",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Dosakayalapalli Colony, Korukonda Mandal - 533292",
        "phone": "+91-9381949339",
        "aadhaar_no": "220800118800",
        "bio": "Doddi Daniel (Telugu Script Name) serves as Social Worker in Korukonda Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_24_uid",
        "name": "Rev. P. John Victor (Paramatichanti Babu)",
        "email": "rev.p.john.victor.paramatichanti.babu.kothapeta@fbglministry.org",
        "username": "rev.p.john.victor.paramatichanti.babu.kothapeta@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-24",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "S/o Prakasha Rao (Late), 10-160, Gowthami Nagar, Kothapeta - 533223, Konaseema Dist, AP",
        "phone": "+91-9866748100",
        "aadhaar_no": "714083648536",
        "bio": "Rev. P. John Victor (Paramatichanti Babu) serves as Social Worker in Kothapeta Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_25_uid",
        "name": "Pastor M. Rajasekhar",
        "email": "pastor.m.rajasekhar.kovvuru@fbglministry.org",
        "username": "pastor.m.rajasekhar.kovvuru@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-25",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "58-13-16, C.T.R.I. Near Pattapu Chettu Center, Rajahmundry - 533103",
        "phone": "+91-7993651337",
        "aadhaar_no": "123456781024",
        "bio": "Pastor M. Rajasekhar serves as Social Worker in Kovvuru Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_26_uid",
        "name": "Nandika Veerabhadra Rao (Moses)",
        "email": "nandika.veerabhadra.rao.moses.mandapeta@fbglministry.org",
        "username": "nandika.veerabhadra.rao.moses.mandapeta@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-26",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "S/o Veeraiah, Dwarapudi, Mandapeta, Vemulapalli (A.P)",
        "phone": "+91-8106600336",
        "aadhaar_no": "443106070480",
        "bio": "Nandika Veerabhadra Rao (Moses) serves as Social Worker in Mandapeta Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_27_uid",
        "name": "Jonnakuti Abhishek",
        "email": "jonnakuti.abhishek.nidamarru@fbglministry.org",
        "username": "jonnakuti.abhishek.nidamarru@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-27",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Adanikolanu, Nidamarru (M), 3-119, 533198",
        "phone": "+91-7799812004",
        "aadhaar_no": "790442565983",
        "bio": "Jonnakuti Abhishek serves as Social Worker in Nidamarru Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_28_uid",
        "name": "Ch. John Lazarus",
        "email": "ch.john.lazarus.purushothapatnam@fbglministry.org",
        "username": "ch.john.lazarus.purushothapatnam@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-28",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Purushothapatnam",
        "phone": "+91-9963928694",
        "aadhaar_no": "448623999514",
        "bio": "Ch. John Lazarus serves as Social Worker in Purushothapatnam Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_29_uid",
        "name": "Kengam Ravi Kishore (Daniel)",
        "email": "kengam.ravi.kishore.daniel.rajahmundry@fbglministry.org",
        "username": "kengam.ravi.kishore.daniel.rajahmundry@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-29",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Dr. No: 44-9-32/3, Chinna Veedhi, Annapurnamma Peta, Rajahmundry, E.G. District, A.P.",
        "phone": "+91-9603148162",
        "aadhaar_no": "123456781028",
        "bio": "Kengam Ravi Kishore (Daniel) serves as Social Worker in Rajahmundry Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_30_uid",
        "name": "Mortha Samuel",
        "email": "mortha.samuel.rajahmundry@fbglministry.org",
        "username": "mortha.samuel.rajahmundry@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-30",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "H.No: 44-15-57, Annapurnamma Peta, Bye-pass Road, Rajamahendravaram",
        "phone": "+91-8790739077",
        "aadhaar_no": "496099545977",
        "bio": "Mortha Samuel serves as Social Worker in Rajahmundry Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_31_uid",
        "name": "Thigiripalli Param Jyothi",
        "email": "thigiripalli.param.jyothi.rajahmundryrural@fbglministry.org",
        "username": "thigiripalli.param.jyothi.rajahmundryrural@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-31",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "5-23, SC Colony, Opp New Water tank, Thomedu, Rajahmundry Rural, E.G. Dist, AP - 533293",
        "phone": "+91-8919937761",
        "aadhaar_no": "635842385446",
        "bio": "Thigiripalli Param Jyothi serves as Social Worker in Rajahmundry Rural Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_32_uid",
        "name": "Kothapalli Yeva Raju",
        "email": "kothapalli.yeva.raju.rajahmundryrural@fbglministry.org",
        "username": "kothapalli.yeva.raju.rajahmundryrural@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-32",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "4-30, SC Colony, Mid Peta, Torredu, Rajahmundry (Rural)",
        "phone": "+91-9553415679",
        "aadhaar_no": "565739182120",
        "bio": "Kothapalli Yeva Raju serves as Social Worker in Rajahmundry Rural Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_33_uid",
        "name": "Muppidi Sudhakar",
        "email": "muppidi.sudhakar.rajahmundryrural@fbglministry.org",
        "username": "muppidi.sudhakar.rajahmundryrural@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-33",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Satellite City, Block No: 76, Plot No: F2, 5th Street, Rajahmundry Rural - 533107",
        "phone": "+91-9603748267",
        "aadhaar_no": "429967821853",
        "bio": "Muppidi Sudhakar serves as Social Worker in Rajahmundry Rural Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_34_uid",
        "name": "Kollapu Raju",
        "email": "kollapu.raju.rajanagaram@fbglministry.org",
        "username": "kollapu.raju.rajanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-34",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "1-282, Ambedkar Street, Diwancheruvu, Rajanagaram, East Godavari - 533296",
        "phone": "+91-9154421051",
        "aadhaar_no": "729878709851",
        "bio": "Kollapu Raju serves as Social Worker in Rajanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_35_uid",
        "name": "Viodhi Ananda Rao",
        "email": "viodhi.ananda.rao.rajanagaram@fbglministry.org",
        "username": "viodhi.ananda.rao.rajanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-35",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Diwancheruvu, Rajanagaram Mandal",
        "phone": "+91-9866850715",
        "aadhaar_no": "123456781036",
        "bio": "Viodhi Ananda Rao serves as Social Worker in Rajanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_36_uid",
        "name": "Kappisetha (Widower)",
        "email": "kappisetha.widower.rajanagaram@fbglministry.org",
        "username": "kappisetha.widower.rajanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-36",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Srirampuram, 533296, East Godavari, AP",
        "phone": "+91-9951291739",
        "aadhaar_no": "123456781037",
        "bio": "Kappisetha (Widower) serves as Social Worker in Rajanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_37_uid",
        "name": "Chirra Nani Babu",
        "email": "chirra.nani.babu.rajanagaram@fbglministry.org",
        "username": "chirra.nani.babu.rajanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-37",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "S/o Chirra Johnbabu, Door No: 6-11, SC Peta, Surya Raopeta, Rajanagaram Mandalam, East Godavari - 533294 (AP)",
        "phone": "+91-9966965355",
        "aadhaar_no": "422226369163",
        "bio": "Chirra Nani Babu serves as Social Worker in Rajanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_38_uid",
        "name": "Palika Chinnababu",
        "email": "palika.chinnababu.rajanagaram@fbglministry.org",
        "username": "palika.chinnababu.rajanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-38",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Yerushalem Church, Kanavaram Post, Rajanagaram Mandal, E.G. Dt",
        "phone": "+91-9177283697",
        "aadhaar_no": "599743306344",
        "bio": "Palika Chinnababu serves as Social Worker in Rajanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_39_uid",
        "name": "Jedla Samuel Raju",
        "email": "jedla.samuel.raju.rajanagaram@fbglministry.org",
        "username": "jedla.samuel.raju.rajanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-39",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Raghudevapuram, Rajanagaram, E. Godavari, AP - 533341",
        "phone": "+91-9949026090",
        "aadhaar_no": "200337232661",
        "bio": "Jedla Samuel Raju serves as Social Worker in Rajanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_40_uid",
        "name": "Karri Manga Raju",
        "email": "karri.manga.raju.rajanagaram@fbglministry.org",
        "username": "karri.manga.raju.rajanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-40",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Chandredu, East Godavari, Rajanagaram Mandal",
        "phone": "+91-9989627790",
        "aadhaar_no": "123456781041",
        "bio": "Karri Manga Raju serves as Social Worker in Rajanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_41_uid",
        "name": "Yandra Prakasam",
        "email": "yandra.prakasam.rajanagaram@fbglministry.org",
        "username": "yandra.prakasam.rajanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-41",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "4-30/4, Ambedkar Street, Kalavacherla, Rajanagaram Mandal, E.G. Dist - 533297",
        "phone": "+91-8897996229",
        "aadhaar_no": "123456781042",
        "bio": "Yandra Prakasam serves as Social Worker in Rajanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_42_uid",
        "name": "gulli ISSAU",
        "email": "gulli.issau.seethanagaram@fbglministry.org",
        "username": "gulli.issau.seethanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-42",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Bobilanka, Prashanth Nagar Colony, Sithanagaram Mandalam, Eluru Dist",
        "phone": "+91-9100950455",
        "aadhaar_no": "314211530768",
        "bio": "gulli ISSAU serves as Social Worker in Seethanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_43_uid",
        "name": "Posupo Indira Priya",
        "email": "posupo.indira.priya.seethanagaram@fbglministry.org",
        "username": "posupo.indira.priya.seethanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-43",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Sigavaram",
        "phone": "+91-8330950772",
        "aadhaar_no": "595342874737",
        "bio": "Posupo Indira Priya serves as Social Worker in Seethanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_44_uid",
        "name": "A. Sesharaju",
        "email": "a.sesharaju.seethanagaram@fbglministry.org",
        "username": "a.sesharaju.seethanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-44",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Katavaram, Sitanagaram (M), E.G. Dist, AP - 533293",
        "phone": "+91-9490351725",
        "aadhaar_no": "486243304351",
        "bio": "A. Sesharaju serves as Social Worker in Seethanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_45_uid",
        "name": "Mallineedi Padma Rao",
        "email": "mallineedi.padma.rao.seethanagaram@fbglministry.org",
        "username": "mallineedi.padma.rao.seethanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-45",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "S/o Buchi Ramayya, 3-129, Subramanyan Street, Seethanagaram, Raghudevapuram, East Godavari, AP",
        "phone": "+91-9553905272",
        "aadhaar_no": "247435746323",
        "bio": "Mallineedi Padma Rao serves as Social Worker in Seethanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_46_uid",
        "name": "Sakiri Nageswararao",
        "email": "sakiri.nageswararao.seethanagaram@fbglministry.org",
        "username": "sakiri.nageswararao.seethanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-46",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "S/o Bhimayya, 2-178, SC Peta, Cheepurupalli, Nagampalli, 533290",
        "phone": "+91-9010331664",
        "aadhaar_no": "460584773636",
        "bio": "Sakiri Nageswararao serves as Social Worker in Seethanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_47_uid",
        "name": "Gundupalli Yesu Babu (Telugu Script Name)",
        "email": "gundupalli.yesu.babu.telugu.script.name.seethanagaram@fbglministry.org",
        "username": "gundupalli.yesu.babu.telugu.script.name.seethanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-47",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Cheepurupalli, Sitanagaram Mandalam",
        "phone": "+91-9133692742",
        "aadhaar_no": "831540286808",
        "bio": "Gundupalli Yesu Babu (Telugu Script Name) serves as Social Worker in Seethanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_48_uid",
        "name": "Dola Nehru",
        "email": "dola.nehru.seethanagaram@fbglministry.org",
        "username": "dola.nehru.seethanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-48",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Raghudevapuram",
        "phone": "+91-9951529439",
        "aadhaar_no": "123456781049",
        "bio": "Dola Nehru serves as Social Worker in Seethanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_49_uid",
        "name": "Galinki Rajesh",
        "email": "galinki.rajesh.seethanagaram@fbglministry.org",
        "username": "galinki.rajesh.seethanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-49",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "1-130, SC Peta, Vangalapudi, Seethanagaram (Mandal)",
        "phone": "+91-8522013747",
        "aadhaar_no": "123456781050",
        "bio": "Galinki Rajesh serves as Social Worker in Seethanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_50_uid",
        "name": "Kangaroo Annavaram",
        "email": "kangaroo.annavaram.seethanagaram@fbglministry.org",
        "username": "kangaroo.annavaram.seethanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-50",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Raghudevapuram, Sitanagaram",
        "phone": "+91-9985273024",
        "aadhaar_no": "340312961041",
        "bio": "Kangaroo Annavaram serves as Social Worker in Seethanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_51_uid",
        "name": "Muvvala Lazaru",
        "email": "muvvala.lazaru.seethanagaram@fbglministry.org",
        "username": "muvvala.lazaru.seethanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-51",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "SC Peta",
        "phone": "+91-9553675095",
        "aadhaar_no": "123456781052",
        "bio": "Muvvala Lazaru serves as Social Worker in Seethanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_52_uid",
        "name": "S. Vijay Kumar",
        "email": "s.vijay.kumar.seethanagaram@fbglministry.org",
        "username": "s.vijay.kumar.seethanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-52",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Bobilanka, Subbarao Peta, Sitanagaram Mandal, E.G. Dist, AP - 533293",
        "phone": "+91-6281985559",
        "aadhaar_no": "974123260605",
        "bio": "S. Vijay Kumar serves as Social Worker in Seethanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_53_uid",
        "name": "Gondela Jyothi Kumar",
        "email": "gondela.jyothi.kumar.seethanagaram@fbglministry.org",
        "username": "gondela.jyothi.kumar.seethanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-53",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Undeshwarapuram, Near Hanuman Junction, Seethanagaram Post, East Godavari Dist",
        "phone": "+91-9704335909",
        "aadhaar_no": "123456781054",
        "bio": "Gondela Jyothi Kumar serves as Social Worker in Seethanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_54_uid",
        "name": "Kovati Sarojini",
        "email": "kovati.sarojini.seethanagaram@fbglministry.org",
        "username": "kovati.sarojini.seethanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-54",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Vangalapudi Village, Seethanagaram Mandal, East Godavari District, AP",
        "phone": "+91-7286060021",
        "aadhaar_no": "469054957234",
        "bio": "Kovati Sarojini serves as Social Worker in Seethanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_55_uid",
        "name": "Bangarapu Sekhar Babu",
        "email": "bangarapu.sekhar.babu.seethanagaram@fbglministry.org",
        "username": "bangarapu.sekhar.babu.seethanagaram@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-55",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "Raghudevapuram, Seethanagaram",
        "phone": "+91-7981639933",
        "aadhaar_no": "536440493854",
        "bio": "Bangarapu Sekhar Babu serves as Social Worker in Seethanagaram Mandal, East Godavari district."
    },
    {
        "_id": "social_worker_56_uid",
        "name": "Khandavalli Salman Raju",
        "email": "khandavalli.salman.raju.generaldata@fbglministry.org",
        "username": "khandavalli.salman.raju.generaldata@fbglministry.org",
        "password": "asdf1234",
        "role": "social_worker",
        "position": "Social Worker",
        "id_no": "FBGL-AP-EG-SW-56",
        "area_manager_id": "area_manager_mude_rajesh_uid",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "state": "AP",
        "district": "EG",
        "state_code": "AP",
        "district_code": "EG",
        "address": "West Ganugudem Village",
        "phone": "+91-8179796662",
        "aadhaar_no": "123456781057",
        "bio": "Khandavalli Salman Raju serves as Social Worker in GeneralData Mandal, East Godavari district."
    }
];

    for (const p of profilesData) {
      const profileObj = {
        _id: p._id,
        name: p.name,
        email: p.email,
        username: p.username || p.email,
        role: p.role,
        position: p.position || undefined,
        bio: p.bio || undefined,
        profile_picture: p.profile_picture || undefined,
        id_no: p.id_no,
        area_manager_id: p.area_manager_id || null,
        project_manager_id: p.project_manager_id || null,
        state: p.state || 'AP',
        district: p.district || 'EG',
        address: p.address,
        phone: p.phone,
        aadhaar_no: p.aadhaar_no,
        state_code: p.state_code || 'AP',
        district_code: p.district_code || 'EG',
        password: defaultPassword
      };
      await new Profile(profileObj).save();
    }
    console.log(`Seeded ${profilesData.length} profiles successfully.`);

    // 5. Insert Projects
    console.log('Seeding projects...');
    const projectsData = [
    {
        "title": "Sample Project 1: Rural Education & Skill Support",
        "description": "Providing educational resources, evening tutoring, and digital skill training for underprivileged children in rural Mandals of East Godavari.",
        "category": "education",
        "status": "ongoing",
        "current_status": "Active",
        "area_of_operation": "East Godavari District, Andhra Pradesh",
        "location": "Rajahmundry & Mandal Centers, AP",
        "target_beneficiaries": "500 children aged 6-16 years",
        "start_date": "2024-01-15",
        "end_date": "2024-12-31",
        "budget": 250000,
        "assigned_to": "FBGL-AP-EG-PM-01",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "show_on_home": true,
        "images": [
            "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?q=80&w=600",
            "https://images.unsplash.com/photo-1542810634-71277d95dcbb?q=80&w=600"
        ]
    },
    {
        "title": "Sample Project 2: Women Empowerment & Vocational Training",
        "description": "Tailoring, sewing machine distribution, and financial literacy workshops for rural women to build independent livelihoods.",
        "category": "economy",
        "status": "ongoing",
        "current_status": "Active",
        "area_of_operation": "East Godavari District, Andhra Pradesh",
        "location": "Kovvuru & Seethanagaram Mandals, AP",
        "target_beneficiaries": "200 women aged 18-45 years",
        "start_date": "2024-02-01",
        "end_date": "2024-11-30",
        "budget": 180000,
        "assigned_to": "FBGL-AP-EG-PM-01",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "show_on_home": true,
        "images": [
            "https://images.unsplash.com/photo-1520263115673-610416f52ab6?q=80&w=600"
        ]
    },
    {
        "title": "Sample Project 3: Community Health & Clean Water Initiative",
        "description": "Installation of deep borewells, distribution of clean drinking water, and regular medical checkup camps across rural Mandals.",
        "category": "social",
        "status": "ongoing",
        "current_status": "Active",
        "area_of_operation": "East Godavari District, Andhra Pradesh",
        "location": "Gandepalli & Devipatnam Mandals, AP",
        "target_beneficiaries": "1000 rural families",
        "start_date": "2024-01-01",
        "end_date": "2024-12-31",
        "budget": 120000,
        "assigned_to": "FBGL-AP-EG-PM-01",
        "project_manager_id": "project_manager_panta_satyanarayana_uid",
        "show_on_home": true,
        "images": [
            "https://images.unsplash.com/photo-1541913496-8099cd5353ed?q=80&w=600"
        ]
    }
];

    for (const proj of projectsData) {
      await new Project(proj).save();
    }
    console.log(`Seeded ${projectsData.length} projects successfully.`);

    // 6. Insert Blog Posts
    console.log('Seeding blog posts...');
    const blogsData = [
    {
        "title": "Sample Blog Post 1: Transforming Communities Across East Godavari",
        "content": "Welcome to our sample blog post highlighting the transformative work being conducted by our dedicated team across 17 Mandals in East Godavari. Through collaborative efforts in education, healthcare, and economic empowerment, lives are being uplifted every day.",
        "type": "blog",
        "status": "published",
        "published": true,
        "author_id": "admin_user_uid",
        "author_name": "Super Admin",
        "cover_image": "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?q=80&w=800",
        "featured_image": "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?q=80&w=800"
    },
    {
        "title": "Sample Blog Post 2: Community Health Camp and Water Awareness Success",
        "content": "Our sample blog update on the recent free medical camp and clean water filtration distribution. Over 350 rural residents received health screenings and access to safe drinking water.",
        "type": "blog",
        "status": "published",
        "published": true,
        "author_id": "admin_user_uid",
        "author_name": "Super Admin",
        "cover_image": "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?q=80&w=800",
        "featured_image": "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?q=80&w=800"
    }
];

    for (const b of blogsData) {
      await new BlogPost(b).save();
    }
    console.log(`Seeded ${blogsData.length} blog posts successfully.`);

    console.log('🎉 Seeding completed successfully!');
  } catch (error) {
    console.error('❌ Seeding failed:', error);
  } finally {
    await mongoose.connection.close();
    console.log('Database connection closed.');
  }
};

seedDatabase();
